import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";

// Mock data for projects
const mockProjects = [
  { id: "1", name: "Project Alpha", status: "active", createdAt: "2023-10-01" },
  { id: "2", name: "Project Beta", status: "completed", createdAt: "2023-09-15" },
  { id: "3", name: "Project Gamma", status: "active", createdAt: "2023-08-20" },
];

// GET handler for fetching project list
export async function GET() {
  // TODO: Replace with actual Prisma query when Project model is added to schema
  return NextResponse.json(mockProjects);
}

// POST handler for creating a new project
export async function POST(request: NextRequest) {
  const body = await request.json();
  // TODO: Replace with actual Prisma query when Project model is added to schema
  const newProject = {
    id: "4", // This should be generated by the database
    name: body.projectName,
    status: "active",
    createdAt: new Date().toISOString(),
    assignees: body.assignees, // Handle multiple assignees
  };
  mockProjects.push(newProject);
  return NextResponse.json(newProject, { status: 201 });
}
